package exceptionDemo.try_catch_finally.stackTrace;

public class Exceptionmain {
    
    public static void main(String[] args) {
        stackTraceTest.factorial(2);
        
    }
}